### PR TITLE
Increase DBUS_TIMEOUT_MSEC variable

### PR DESCRIPTION
**Pull request by aerocyber**
This is done so that on some systems, particularly the older ones, the installer fails to continue in `Custom Install` due to not showing ALL partitions.

### CODE REVIEW

**Comment by aerocyber** [comment]
Note: This is a follow-up for pr #701 as I noticed in my recent re-installation of elementary, it fails even at the previous value of 300 seconds (5 minutes). This one did work for me. Should it be even higher value if a really old system is taken into account? Won't probing the disk stop after it's successful or will it run for the entire 10 minute duration?

**Comment by lenemter** [comment]
> Won't probing the disk stop after it's successful or will it run for the entire 10 minute duration?

It will stop stop when it succeeds. This timeout sets maximum time that installer will wait for probing.

**Review by lenemter — APPROVED** [review]

**Comment by lenemter** [comment]
For some reason development-target CI fails and I can't merge this. @danirabbit Can you merge this, please?

**Comment by danirabbit** [comment]
@lenemter temporarily removed the requirement for `development-target`

**Pull request merged**
