### PR TITLE
Replace width_chars with clamp

### LINKED ISSUE #793: Clicking a partition in the custom install glitches the installer window
### What Happened?

Clicking a partition in the custom install glitches the installer window, which makes me being unable to set up partitions.

### Steps to Reproduce

1. Boot from Early Access 8 ISO (I used `elementaryos-8.0-daily.20240824.iso`)
2. Select the custom install
3. In the "Select Partitions" view, click "Modify Partitions…" to create partitions if none exists
4. In the "Select Partitions" view, click the storage bar (the yellow/green portion in the following screenshot)  
VirtualBox_test_25_08_2024_10_52_43
5. See the installer window get bigger and unable to setup partitions  
VirtualBox_test_25_08_2024_10_54_19

### Expected Behavior

The window should not glitch and the following popover should be shown where we can setup partitions:

VirtualBox_test_25_08_2024_10_57_47

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Aug 25 02:09:05 elementary io.elementary.g[1858]: Can't update stage views actor unnamed [MetaWindowActorX11] is on because it needs an allocation.
Aug 25 02:09:05 elementary io.elementary.g[1858]: Can't update stage views actor unnamed [MetaSurfaceActorX11] is on because it needs an allocation.
Aug 25 02:09:05 elementary io.elementary.i[2053]: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed
Aug 25 02:09:05 elementary io.elementary.i[2053]: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed
Aug 25 02:09:05 elementary io.elementary.i[2053]: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed
Aug 25 02:09:05 elementary io.elementary.i[2053]: gtk_widget_size_allocate(): attempt to allocate GtkPopoverContent contents 0x562c36a38a20 with width 253 and height -23
Aug 25 02:09:05 elementary io.elementary.i[2053]: gtk_widget_size_allocate(): attempt to allocate GtkGrid grid 0x562c364c6b80 with width -2 and height -8
Aug 25 02:09:05 elementary io.elementary.installer.desktop[2053]: *** BUG ***
Aug 25 02:09:05 elementary io.elementary.installer.desktop[2053]: In pixman_region32_init_rect: Invalid rectangle passed
Aug 25 02:09:05 elementary io.elementary.installer.desktop[2053]: Set a breakpoint on '_pixman_log_error' to debug
```

[installer-glitch.log](https://github.com/user-attachments/files/16738721/installer-glitch.log)

### Hardware Info

_No response_

### PR DESCRIPTION
**Pull request by danirabbit**
Removes a max_width_chars hack and instead puts the content area in a clamp

### CODE REVIEW

**Comment by ryonakano** [comment]
Hmm for me the issue is still reproducible:

[elementary OS 8 Early Access-screen0.webm](https://github.com/user-attachments/assets/7430f9ab-37ef-48a2-8be7-bb4a05ff8726)

**Comment by alainm23** [comment]
Perhaps you could use a `Gtk.ScrolledWindow` with `vscrollbar_policy` and `hvscrollbar_policy` in `NEVER` to prevent the text label from overflowing.

**Comment by danirabbit** [comment]
@alainm23 yeah the partition bars are actually already inside a scrolled window. Will dig in further today though

**Comment by ryonakano** [comment]
> Ah damn I wasn't able to reproduce at all in this branch 🤔 Is this under X11 or Wayland?

I'm on X11. Maybe it should make sure it works on X11 because the current Greeter runs on it.

**Review by ryonakano — APPROVED** [review]
Confirmed all texts in the all views are wrapped nicely both when the window is narrow and wide.

**Pull request merged**
