### PR TITLE
Port to GTK 4

### LINKED ISSUE #628: Port Installer to GTK4

### PR DESCRIPTION
**Pull request by danirabbit**
Fixes #628

### CODE REVIEW

**Comment by danirabbit** [comment]
Tested the constraint layout with a number of different partitions with small and large partitions on either end and with unused space:

Screenshot from 2024-06-06 16 54 19

**Comment by ryonakano** [comment]
We also need to update the dependencies in README :)

**Comment by danirabbit** [comment]
@ryonakano done!

**Comment by zeebok** [comment]
Just tried testing this and noticed this missing icon? 
Screenshot from 2024-07-27 20 28 06

**Review by zeebok — APPROVED** [review]
Nothing in the code sticks out, and running in test mode worked well except for some reason trying to modify partitions just opened gparted on my machine. But I assume that is just from me running it locally instead of in a normal live session or in VM

**Comment by danirabbit** [comment]
@zeebok ah yeah "modify" always opens gparted. There's no partition resizing here. You can only choose what to apply on each partition but can't resize or create or delete partitions

**Pull request merged**
