### PR TITLE
Make use of libdistinst

### PR DESCRIPTION
**Pull request by tintou**

### CODE REVIEW

**Comment by jackpot51** [comment]
:tada: :cake: :tada: :cake:

**Comment by jackpot51** [comment]
I need to test `distinst` in elementary artful, how can I build that?

**Comment by tintou** [comment]
@jackpot51 We have daily builds of libdistinst here https://code.launchpad.net/~elementary-os/+recipe/distinst-daily

**Comment by tintou** [comment]
@codygarver can help you for the iso side

**Pull request merged**
